# Generated by Django 6.0.7 on 2026-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='lesson_resources/'),
        ),
    ]
